name: Automated Crypto ETL Pipeline

on:
  schedule:
    # Mengatur jadwal otomatis: Berjalan setiap hari pada jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 * * *'
  workflow_dispatch: 
    # workflow_dispatch memunculkan tombol "Run workflow" agar bisa kita jalankan manual di web GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest # Robot akan menggunakan sistem operasi Linux Ubuntu
    
    steps:
    - name: Mengambil Kode dari Repository
      uses: actions/checkout@v3
      
    - name: Menyiapkan Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Menginstal Library
      run: pip install -r requirements.txt
        
    - name: Menjalankan Script ETL
      run: python etl_pipeline.py
      
    - name: Menyimpan Database Baru ke GitHub
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add market_db.sqlite
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update database harian"
        git push